site_name: Ivory
site_url: https://ivory.daizutabi.net/
site_description: A Lightweight machine learning framework
site_author: daizutabi
site_dir: ../ivory-site/site

repo_url: https://github.com/daizutabi/ivory/
edit_uri: ""

theme: ivory

plugins:
  - search
  - pheasant:
      version: ivory
      jupyter: true
      header:
        disabled: true

nav:
  - Home: index.md
  - Tutorial:
      Overview: tutorial/overview.py
      Client: tutorial/client_experiment_run.py
      # Model: tutorial/model.py
      # Metrics: tutorial/metrics.py
      # Trainer: tutorial/trainer.md
      # Run: tutorial/run.md
      # Experiment: tutorial/experiment.md


markdown_extensions:
  - admonition
