site_name: Ivory
site_url: https://ivory.daizutabi.net/
site_description: A Lightweight machine learning framework
site_author: daizutabi
site_dir: ../ivory-site/site

repo_url: https://github.com/daizutabi/ivory/
edit_uri: ""

theme: readthedocs

plugins:
  - search
  - pheasant:
      version: ivory
  - mkapi

nav:
  - Quickstart: index.md
  # - Tutorial:
  #   - Quickstart: quickstart.py
  - Python API:
    - Data: api/data.md
    - Data: api/data.md
  # - Tutorial:
  #     Overview: tutorial/overview.py
  #     Client: tutorial/client_experiment_run.py
      # Model: tutorial/model.py
      # Metrics: tutorial/metrics.py
      # Trainer: tutorial/trainer.md
      # Run: tutorial/run.md
      # Experiment: tutorial/experiment.md

extra_css: [extra.css]

markdown_extensions:
  - admonition
  - pymdownx.superfences
