site_name: Ivory
site_url: https://ivory.daizutabi.net/
site_description: A Lightweight machine learning framework
site_author: daizutabi
site_dir: ../ivory-site/site

repo_url: https://github.com/daizutabi/ivory/
edit_uri: ""

theme:
  name: ivory
  highlightjs: true
  hljs_languages:
    - yaml

plugins:
  - search
  - pheasant:
      version: ivory
      cur_dir: config
      sys_paths: [examples]
  - mkapi

nav:
  - index.md
  - quickstart.md
  - Tutorial:
    - tutorial/data.md
    - tutorial/instance.md
    - tutorial/model.md
    - tutorial/callback.md
    - tutorial/training.md
    - tutorial/core.md
    - tutorial/task.md
    - tutorial/tuning.md
    - tutorial/ui.md
    - tutorial/tracking.md
    - tutorial/library.md
    - tutorial/cli.md
  - Python API:
    - ivory.core:
      - api/ivory.core.data.md
      - api/ivory.core.base.md
      - api/ivory.core.client.md
      - api/ivory.core.run.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
