datasets:
  data:
    class: rectangle.data.Data
    n_splits: 4
  dataset:
    transform: rectangle.data.transform
  fold: 0
estimator:
  class: ivory.lightgbm.estimator.Regressor
  boosting_type: gbdt
  num_leaves: 10
  learning_rate: 0.1
  max_depth: 4
  num_boost_round: 10
  verbose_eval: 2
results:
metrics:
  mse:
