environment:
  class: ivory.core.Environment
  tracker:
    class: ivory.core.Tracker
    tracking_uri: mysql+mysqldb://daizu:tabi@localhost/mlflow
    artifact_location: ~/.mlruns
  tuner:
    class: ivory.core.Tuner
    storage: mysql+mysqldb://daizu:tabi@localhost/optuna
    pruner:
      class: optuna.pruners.MedianPruner
experiment:
  class: ivory.core.Experiment
  data:
    class: ivory.core.Data
    data:
      def: simple.create_data
      num_samples: 10000
  objective:
    class: ivory.core.Objective
    suggest:
      def: simple.suggest
run:
  class: ivory.torch.Run
  dataloader:
    class: ivory.core.DataLoader
    dataset:
      def: ivory.torch.Dataset
    dataloader:
      def: ivory.torch.dataloader
      batch_size: 32
    fold: 0
  model:
    class: simple.Model
    hidden_sizes: [100, 100]
  optimizer:
    class: torch.optim.SGD
    params: $.model.parameters()
    lr: 1e-3
  scheduler:
    class: torch.optim.lr_scheduler.ReduceLROnPlateau
    optimizer: $
    factor: 0.5
    patience: 4
  metrics:
    class: ivory.torch.Metrics
    criterion:
      def: torch.nn.functional.mse_loss
  monitor:
    class: ivory.callbacks.Monitor
  early_stopping:
    class: ivory.callbacks.EarlyStopping
    patience: 8
  trainer:
    class: ivory.torch.Trainer
    max_epochs: 10
    verbose: 2
